# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk13

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту sedelnik0v@yandex.ru если сборка упала
notifications:
  email:
    recipients:
      -sedelnik0v@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always

env:
    global:
      - CODECOV_TOKEN="4601f75f-ad11-424d-bbd4-933b95a8b0d5"